// Generated by CoffeeScript 1.9.3
(function() {
  pages.loginform = {
    "header": 'Login'
  };

  pages.loginform.content = '<div id="login-error" class="hidden"></div> <form onsubmit="loginFormSubmit();return false;"> Jméno: <input type="text" id="username"><br> Heslo: <input type="password" id="password"> <input type="submit" value="OK"> </form>';

}).call(this);

//# sourceMappingURL=loginform.page.js.map
