// Generated by CoffeeScript 1.9.3
(function() {
  document.write = '<div id="debuginfo"> <table> <tr> <td> fps: </td> <td id="fps"> </td> </tr> <tr> <td> canvas_mouse: </td> <td id="canvas_mouse"> </td> </tr> <tr> <td> map_mouse: </td> <td id="map_mouse"> </td> </tr> <tr> <td> size_spring: </td> <td id="size_spring"> </td> </tr> <tr> <td> zoom: </td> <td id="map_zoom"> </td> </tr> <tr> <td> rotation: </td> <td id="map_rotation"> </td> </tr> <tr> <td> slope: </td> <td id="map_slope"> </td> </tr> <tr> <td> x: </td> <td id="map_x"> </td> </tr> <tr> <td> y: </td> <td id="map_y"> </td> </tr> <tr> <td> size: </td> <td id="map_size" > </td> </tr> </table> </div>';

}).call(this);

//# sourceMappingURL=debug.js.map
